"use client";

import { useState } from "react";
import Image from "next/image";
import * as Dialog from "@radix-ui/react-dialog";
import { ChevronLeft, ChevronRight, Crown, Expand, ImageIcon, X } from "lucide-react";
import type { GameDlc, GameEdition } from "@/lib/igdb";

export function GameContentGallery({ title, screenshots, dlcs, editions }: { title: string; screenshots: string[]; dlcs: GameDlc[]; editions: GameEdition[] }) {
  const [activeScreenshot, setActiveScreenshot] = useState<number | null>(null);
  const [activeDlc, setActiveDlc] = useState<GameDlc | null>(null);

  return (
    <>
      {editions.length > 0 && <section className="space-y-3"><div className="flex items-center gap-2"><Crown className="size-5 text-[var(--gold)]" /><h2 className="font-display text-lg font-bold">Editions &amp; Premium Packages</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{editions.map((edition) => <article key={edition.id} className="relative overflow-hidden rounded-[var(--radius-lg)] border border-[rgb(var(--gold-rgb)/0.35)] bg-[linear-gradient(145deg,rgb(var(--gold-rgb)/0.13),var(--glass))] p-4">{edition.coverUrl && <div className="relative mb-3 aspect-[16/7] overflow-hidden rounded-[var(--radius-md)]"><Image src={edition.coverUrl} alt={edition.name} fill sizes="360px" className="object-cover object-top" /></div>}<p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--gold)]">{edition.versionTitle ?? "Special Edition"}</p><h3 className="mt-1 font-display text-lg font-bold">{edition.name}</h3>{edition.summary && <p className="mt-2 line-clamp-3 text-xs leading-relaxed text-[var(--text-secondary)]">{edition.summary}</p>}{edition.features.length > 0 && <ul className="mt-3 space-y-1 border-t border-[var(--border)] pt-3">{edition.features.slice(0, 5).map((feature) => <li key={feature.title} className="text-xs text-[var(--text-secondary)]"><span className="text-[var(--gold)]">•</span> {feature.title}{feature.description ? ` — ${feature.description}` : ""}</li>)}</ul>}</article>)}</div></section>}

      {dlcs.length > 0 && <section className="space-y-3"><h2 className="font-display text-lg font-bold">DLC &amp; Expansions</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{dlcs.map((dlc) => <button key={dlc.id} type="button" onClick={() => setActiveDlc(dlc)} className="glass group flex min-h-32 gap-3 rounded-[var(--radius-md)] p-3 text-left transition hover:border-[var(--accent)]">{dlc.coverUrl ? <div className="relative aspect-[3/4] w-20 shrink-0 overflow-hidden rounded-[var(--radius-sm)]"><Image src={dlc.coverUrl} alt={dlc.name} fill sizes="80px" className="object-cover transition duration-300 group-hover:scale-105" /></div> : <div className="grid aspect-[3/4] w-20 shrink-0 place-items-center rounded-[var(--radius-sm)] bg-[var(--bg-surface)]"><ImageIcon className="size-5 text-[var(--text-muted)]" /></div>}<div className="min-w-0 flex-1"><span className="text-[9px] font-bold uppercase tracking-wider text-[var(--accent)]">{dlc.kind}</span><h3 className="mt-1 text-sm font-semibold leading-tight">{dlc.name}</h3>{dlc.summary && <p className="mt-1 line-clamp-3 text-xs leading-relaxed text-[var(--text-muted)]">{dlc.summary}</p>}<span className="mt-2 inline-flex items-center text-[10px] font-semibold text-[var(--text-secondary)]">View details <ChevronRight className="size-3" /></span></div></button>)}</div></section>}

      {screenshots.length > 0 && <section className="space-y-3"><h2 className="font-display text-lg font-bold">Screenshots</h2><div className="-mx-1 flex snap-x gap-3 overflow-x-auto px-1 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{screenshots.map((source, index) => <button key={source} type="button" onClick={() => setActiveScreenshot(index)} aria-label={`Expand ${title} screenshot ${index + 1}`} className="group relative aspect-video w-80 shrink-0 snap-start overflow-hidden rounded-[var(--radius-md)] border border-[var(--border)]"><Image src={source} alt={`${title} screenshot ${index + 1}`} fill sizes="320px" className="object-cover transition duration-300 group-hover:scale-105" /><span className="absolute right-2 top-2 grid size-9 place-items-center rounded-full bg-black/65 text-white opacity-0 backdrop-blur transition group-hover:opacity-100 group-focus-visible:opacity-100"><Expand className="size-4" /></span></button>)}</div></section>}

      <Dialog.Root open={activeScreenshot !== null} onOpenChange={(open) => !open && setActiveScreenshot(null)}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/90 backdrop-blur-sm" /><Dialog.Content onKeyDown={(event) => { if (activeScreenshot === null) return; if (event.key === "ArrowLeft") setActiveScreenshot((activeScreenshot - 1 + screenshots.length) % screenshots.length); if (event.key === "ArrowRight") setActiveScreenshot((activeScreenshot + 1) % screenshots.length); }} className="fixed inset-4 z-50 grid place-items-center outline-none"><Dialog.Title className="sr-only">{title} screenshot</Dialog.Title>{activeScreenshot !== null && <div className="relative size-full"><Image src={screenshots[activeScreenshot]} alt={`${title} expanded screenshot ${activeScreenshot + 1}`} fill sizes="100vw" quality={95} className="object-contain" /></div>}<button type="button" onClick={() => setActiveScreenshot((activeScreenshot! - 1 + screenshots.length) % screenshots.length)} aria-label="Previous screenshot" className="absolute left-1 top-1/2 grid size-12 -translate-y-1/2 place-items-center rounded-full bg-black/65 text-white backdrop-blur transition hover:bg-black/85 sm:left-4"><ChevronLeft className="size-6" /></button><button type="button" onClick={() => setActiveScreenshot((activeScreenshot! + 1) % screenshots.length)} aria-label="Next screenshot" className="absolute right-1 top-1/2 grid size-12 -translate-y-1/2 place-items-center rounded-full bg-black/65 text-white backdrop-blur transition hover:bg-black/85 sm:right-4"><ChevronRight className="size-6" /></button><span className="absolute bottom-2 rounded-full bg-black/65 px-3 py-1 font-mono text-xs text-white/80">{activeScreenshot !== null ? activeScreenshot + 1 : 0} / {screenshots.length}</span><Dialog.Close className="absolute right-2 top-2 grid size-11 place-items-center rounded-full bg-black/70 text-white"><X className="size-5" /></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>

      <Dialog.Root open={activeDlc !== null} onOpenChange={(open) => !open && setActiveDlc(null)}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm" /><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[88dvh] w-[92vw] max-w-3xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-[var(--radius-xl)] border border-[var(--border)] bg-[var(--bg-elevated)] shadow-2xl outline-none">{activeDlc && <div className="grid sm:grid-cols-[240px_1fr]">{(activeDlc.artworkUrl || activeDlc.coverUrl) && <div className={`relative min-h-72 bg-black/25 ${activeDlc.artworkUrl ? "sm:min-h-full" : "mx-auto aspect-[3/4] w-52 sm:mx-0 sm:w-full"}`}><Image src={activeDlc.artworkUrl ?? activeDlc.coverUrl!} alt={activeDlc.name} fill sizes="(max-width:640px) 208px, 240px" quality={95} className={activeDlc.artworkUrl ? "object-cover" : "object-contain"} /></div>}<div className="p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-widest text-[var(--accent)]">{activeDlc.kind}</p><Dialog.Title className="mt-1 font-display text-2xl font-bold">{activeDlc.name}</Dialog.Title><div className="mt-2 flex flex-wrap gap-2 text-xs text-[var(--text-muted)]">{activeDlc.year && <span>{activeDlc.year}</span>}{activeDlc.platforms.map((platform) => <span key={platform} className="rounded-full border border-[var(--border)] px-2 py-0.5">{platform}</span>)}</div><Dialog.Description className="mt-4 text-sm leading-relaxed text-[var(--text-secondary)]">{activeDlc.summary ?? "No additional description is available from IGDB yet."}</Dialog.Description></div></div>}<Dialog.Close className="absolute right-3 top-3 grid size-10 place-items-center rounded-full bg-black/70 text-white"><X className="size-5" /></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
    </>
  );
}
